# Generated by Django 5.1.4 on 2025-01-12 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='question',
        ),
        migrations.AddField(
            model_name='question',
            name='options',
            field=models.ManyToManyField(blank=True, related_name='questions', to='Lending.option'),
        ),
    ]
