# Generated by Django 5.1.4 on 2025-01-12 01:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0002_remove_option_question_question_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='primary_question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='primary_in_quizzes', to='Lending.question', verbose_name='Основной вопрос'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(help_text="Укажите подсказку для пользователя, например 'Введите имя'", max_length=255),
        ),
    ]
