# Generated by Django 5.1.4 on 2025-01-12 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0003_quiz_primary_question_alter_option_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='quiz',
            name='primary_question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='primary_in_quizzes', to='Lending.question', verbose_name='Вопрос'),
        ),
    ]
