# Generated by Django 5.1.4 on 2025-01-12 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0004_remove_quiz_created_at_alter_quiz_primary_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='description',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='primary_question',
        ),
        migrations.AddField(
            model_name='quiz',
            name='question',
            field=models.ManyToManyField(blank=True, related_name='quest', to='Lending.question'),
        ),
    ]
