# Generated by Django 5.1.4 on 2025-01-12 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0005_remove_quiz_description_remove_quiz_primary_question_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Важно указать для input, которые используются в конечном окне квиза.( В иных случаях указывать не нужно)', max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='EndFrame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('inputs', models.ManyToManyField(blank=True, related_name='input', to='Lending.option')),
            ],
        ),
    ]
