# Generated by Django 5.1.4 on 2025-01-12 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0006_option_placeholder_endframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='endFrame',
            field=models.ManyToManyField(blank=True, related_name='endFrame', to='Lending.endframe'),
        ),
    ]
