# Generated by Django 5.1.4 on 2025-01-12 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0007_quiz_endframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='quiz',
        ),
    ]
