# Generated by Django 5.1.4 on 2025-01-12 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0008_remove_question_quiz'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='option',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
