# Generated by Django 5.1.4 on 2025-01-12 03:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0009_alter_option_options_option_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='option',
            options={},
        ),
        migrations.RemoveField(
            model_name='option',
            name='my_order',
        ),
    ]
