# Generated by Django 5.1.4 on 2025-01-12 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0010_alter_option_options_remove_option_my_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='type_text',
            field=models.CharField(blank=True, help_text='Укажите тип данных, например метры. Нужен только для вопросов типа Dropdown. (Необязательный параметр)', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='option',
            name='placeholder',
            field=models.CharField(blank=True, help_text='Важно указать для input если в них вводят текст. (Необязательный параметр)', max_length=255, null=True),
        ),
    ]
