# Generated by Django 5.1.4 on 2025-01-12 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0011_option_type_text_alter_option_placeholder'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['my_order']},
        ),
        migrations.AddField(
            model_name='question',
            name='my_order',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
