# Generated by Django 5.1.4 on 2025-01-12 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0012_alter_question_options_question_my_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={},
        ),
        migrations.RemoveField(
            model_name='question',
            name='my_order',
        ),
    ]
