# Generated by Django 5.1.4 on 2025-01-12 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0013_alter_question_options_remove_question_my_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False, unique=True),
        ),
    ]
