# Generated by Django 5.1.4 on 2025-01-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0015_alter_question_id_remove_quiz_endframe_quiz_endframe'),
    ]

    operations = [
        migrations.AddField(
            model_name='option',
            name='id_for_get',
            field=models.CharField(blank=True, choices=[('phone', 'phone'), ('whatapp', 'whatapp'), ('tg', 'tg')], help_text='Укажите тип контактной информации. Актуально только для endFrame. (Необязательный параметр)', max_length=255, null=True),
        ),
    ]
