# Generated by Django 5.1.4 on 2025-01-12 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0016_option_id_for_get'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='endframe',
            name='inputs',
        ),
        migrations.AddField(
            model_name='endframe',
            name='text_button',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endframe',
            name='text_phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endframe',
            name='text_telegram',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='endframe',
            name='text_whatsapp',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
