# Generated by Django 5.1.4 on 2025-01-12 06:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0017_remove_endframe_inputs_endframe_text_button_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='option',
            name='id_for_get',
        ),
    ]
