# Generated by Django 5.1.4 on 2025-01-15 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0018_remove_option_id_for_get'),
    ]

    operations = [
        migrations.CreateModel(
            name='LendingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/files/', verbose_name='Файл')),
            ],
        ),
    ]
