# Generated by Django 5.1.4 on 2025-01-15 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0019_lendingpage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExampleOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desctiprtion', models.CharField(max_length=1000, verbose_name='Опимсание работы')),
                ('file', models.FileField(upload_to='lending/data/examplesOfWork/', verbose_name='Файл приимера работ')),
            ],
        ),
        migrations.CreateModel(
            name='Icons',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название логотипа')),
                ('file', models.FileField(upload_to='lending/data/icons/', verbose_name='Файл иконки')),
            ],
        ),
        migrations.AlterModelOptions(
            name='lendingpage',
            options={'verbose_name': 'Страница', 'verbose_name_plural': 'Страницы'},
        ),
        migrations.RemoveField(
            model_name='lendingpage',
            name='file',
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='domain',
            field=models.CharField(default=1, max_length=255, verbose_name='Доменное имя, вместе с под доменном.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='logo',
            field=models.FileField(default=1, upload_to='lending/data/logo/', verbose_name='Логитип'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='number',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер телефона'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='preview_slider',
            field=models.FileField(default=1, upload_to='lending/data/slider/', verbose_name='Картинка слайда'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='title',
            field=models.CharField(default=1, max_length=255, verbose_name='Название'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='title_slider',
            field=models.CharField(default=1, max_length=255, verbose_name='Название блока с слайдом'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='title_swaper',
            field=models.CharField(default=1, max_length=255, verbose_name='Название блока  с примерами работ'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='examplesWork',
            field=models.ManyToManyField(related_name='ExampleOfWork', to='Lending.icons'),
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='icons',
            field=models.ManyToManyField(related_name='LendingPage', to='Lending.icons'),
        ),
    ]
