# Generated by Django 5.1.4 on 2025-01-15 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0020_exampleofwork_icons_alter_lendingpage_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exampleofwork',
            options={'verbose_name': 'Пример работы', 'verbose_name_plural': 'Примеры работ'},
        ),
        migrations.AlterModelOptions(
            name='icons',
            options={'verbose_name': 'Иконка', 'verbose_name_plural': 'Иконки'},
        ),
    ]
