# Generated by Django 5.1.4 on 2025-01-15 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0021_alter_exampleofwork_options_alter_icons_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageForExampleOfWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lending/data/examplesOfWork/', verbose_name='Файл приимера работ')),
            ],
            options={
                'verbose_name': 'Изображение примера работы',
                'verbose_name_plural': 'Изображения примеров работ',
            },
        ),
        migrations.RemoveField(
            model_name='exampleofwork',
            name='file',
        ),
        migrations.AddField(
            model_name='exampleofwork',
            name='images',
            field=models.ManyToManyField(related_name='ExampleOfWork', to='Lending.imageforexampleofwork'),
        ),
    ]
