# Generated by Django 5.1.4 on 2025-01-16 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0022_imageforexampleofwork_remove_exampleofwork_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendingpage',
            name='examplesWork',
        ),
        migrations.AlterField(
            model_name='lendingpage',
            name='icons',
            field=models.ManyToManyField(related_name='LendingPage', to='Lending.icons', verbose_name='Иконки'),
        ),
    ]
