# Generated by Django 5.1.4 on 2025-01-16 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0023_remove_lendingpage_exampleswork_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='question',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Question', to='Lending.question'),
            preserve_default=False,
        ),
    ]
