# Generated by Django 5.1.4 on 2025-01-16 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0024_lendingpage_question'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lendingpage',
            name='question',
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Quiz', to='Lending.quiz'),
            preserve_default=False,
        ),
    ]
