# Generated by Django 5.1.4 on 2025-01-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0025_remove_lendingpage_question_lendingpage_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='number_whatsap',
            field=models.CharField(default=1, max_length=255, verbose_name='Номер whatsapp'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='username_telegram',
            field=models.CharField(default=1, max_length=255, verbose_name='Username телеграмм'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exampleofwork',
            name='desctiprtion',
            field=models.CharField(max_length=1000, verbose_name='Описание работы'),
        ),
    ]
