# Generated by Django 5.1.4 on 2025-01-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0026_lendingpage_number_whatsap_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='Описание'),
            preserve_default=False,
        ),
    ]
