# Generated by Django 5.1.4 on 2025-01-20 11:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0027_lendingpage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='blackout',
            field=models.FloatField(default=1, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)], verbose_name='затемнение'),
            preserve_default=False,
        ),
    ]
