# Generated by Django 5.1.4 on 2025-01-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0028_lendingpage_blackout'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='questionJson',
            field=models.JSONField(default=1, verbose_name='Вопросы'),
            preserve_default=False,
        ),
    ]
