# Generated by Django 5.1.4 on 2025-01-24 03:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0029_quiz_questionjson'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='options',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='question',
        ),
        migrations.DeleteModel(
            name='Option',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
