# Generated by Django 5.1.4 on 2025-01-24 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0030_remove_question_options_remove_quiz_question_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excelTable', models.FileField(upload_to='lending/settings/', verbose_name='Эксель таблица')),
                ('id_app', models.IntegerField(default=2, verbose_name='Номер колонки excel с app_id')),
                ('id_title', models.IntegerField(default=3, verbose_name='Номер колонки excel с заголовками')),
                ('id_subtitle', models.IntegerField(default=4, verbose_name='Номер колонки excel с под заголовками')),
                ('min_rows', models.IntegerField(verbose_name='Номер строки с, которой начинается порядок')),
                ('max_rows', models.IntegerField(verbose_name='Номер конечной строки')),
            ],
        ),
        migrations.CreateModel(
            name='UploadInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app', models.IntegerField()),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.CharField(max_length=255)),
            ],
        ),
    ]
