# Generated by Django 5.1.4 on 2025-01-24 05:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0031_settings_uploadinfo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='settings',
            options={'verbose_name': 'Настройка', 'verbose_name_plural': 'Настройки'},
        ),
        migrations.AlterModelOptions(
            name='uploadinfo',
            options={'verbose_name': 'Информация Excel', 'verbose_name_plural': 'Информация Excel'},
        ),
        migrations.AddField(
            model_name='quiz',
            name='campaign',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='Компания'),
        ),
    ]
