# Generated by Django 5.1.4 on 2025-01-24 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0032_alter_settings_options_alter_uploadinfo_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='chatid',
            field=models.IntegerField(default=1, verbose_name='Chat id телеграмм канала'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='botTelegramToken',
            field=models.CharField(default=1, max_length=255, verbose_name='Api token telegram bot'),
            preserve_default=False,
        ),
    ]
