# Generated by Django 5.1.4 on 2025-01-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0033_lendingpage_chatid_settings_bottelegramtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='head',
            field=models.TextField(default=1, verbose_name='Head сайта, для метрики'),
            preserve_default=False,
        ),
    ]
