# Generated by Django 5.1.4 on 2025-01-24 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0034_lendingpage_head'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lendingpage',
            name='head',
            field=models.TextField(blank=True, null=True, verbose_name='Head сайта, для метрики'),
        ),
    ]
