# Generated by Django 5.1.4 on 2025-01-25 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0035_alter_lendingpage_head'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='examplesOfWork',
            field=models.JSONField(default=1, verbose_name='Примеры работ'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='ExampleOfWork',
        ),
    ]
