# Generated by Django 5.1.4 on 2025-01-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0036_lendingpage_examplesofwork_delete_exampleofwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='target_feedback',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Цель для формы обратной связи'),
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='target_quiz',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Цель для формы квиза'),
        ),
    ]
