# Generated by Django 5.1.4 on 2025-01-26 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0037_lendingpage_target_feedback_lendingpage_target_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='target_quiz_set',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Цель для формы квиза в процессе'),
        ),
    ]
