# Generated by Django 5.1.4 on 2025-01-29 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0038_lendingpage_target_quiz_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='lendingpage',
            name='accentColor',
            field=models.CharField(default=1, max_length=255, verbose_name='Основной цвет'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='imageArrow',
            field=models.FileField(default=1, upload_to='lending/data/images/', verbose_name='Изображение стрелка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='imageCheckBox',
            field=models.FileField(default=1, upload_to='lending/data/images/', verbose_name='Изображение чек бокс'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='imageCheckBoxPolit',
            field=models.FileField(default=1, upload_to='lending/data/images/', verbose_name='Изображение чек бокс политики'),
            preserve_default=False,
        ),
    ]
