# Generated by Django 5.1.4 on 2025-02-03 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0039_lendingpage_accentcolor_lendingpage_imagearrow_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImagesQuiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='lending/data/quizPhotos/', verbose_name='Файл квиза')),
                ('utm_content', models.JSONField(default=list, verbose_name='UTM контент метка')),
            ],
            options={
                'verbose_name': 'Изображение квиза',
                'verbose_name_plural': 'Изображения квизов',
            },
        ),
        migrations.AlterModelOptions(
            name='endframe',
            options={'verbose_name': 'Конечные frame квизов', 'verbose_name_plural': 'Конечный frame квиза'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Квизы', 'verbose_name_plural': 'Квиз'},
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='campaign',
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='description_meta',
            field=models.CharField(default=1, max_length=255, verbose_name='Мета описание сайта ( нельзя использовать html теги )'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lendingpage',
            name='title_meta',
            field=models.CharField(default=1, max_length=255, verbose_name='Мета название сайта ( нельзя использовать html теги )'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='quiz',
            name='utm_content',
            field=models.JSONField(blank=True, default=list, null=True, verbose_name='UTM контент метка'),
        ),
        migrations.AlterField(
            model_name='imageforexampleofwork',
            name='file',
            field=models.FileField(upload_to='lending/data/examplesOfWork/', verbose_name='Файл примера работ'),
        ),
    ]
