# Generated by Django 5.1.4 on 2025-09-28 10:58

import Lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0040_imagesquiz_alter_endframe_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UtmExampleWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examplesOfWork', models.JSONField(verbose_name='Примеры работ')),
                ('utm_content', models.JSONField(default=list, verbose_name='UTM контент метка')),
            ],
            options={
                'verbose_name': 'UTM примеры работы',
                'verbose_name_plural': 'UTM примеры работ',
            },
        ),
        migrations.AddField(
            model_name='imageforexampleofwork',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='imagesquiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
        migrations.AlterField(
            model_name='icons',
            name='file',
            field=models.FileField(upload_to=Lending.models.random_icon_filename, verbose_name='Файл иконки'),
        ),
        migrations.AlterField(
            model_name='imageforexampleofwork',
            name='file',
            field=models.FileField(upload_to=Lending.models.random_example_filename, verbose_name='Файл примера работ'),
        ),
        migrations.AlterField(
            model_name='imagesquiz',
            name='file',
            field=models.FileField(upload_to=Lending.models.random_quiz_filename, verbose_name='Файл квиза'),
        ),
    ]
