# Generated by Django 5.1.4 on 2025-07-04 14:04

import Lending.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0040_imagesquiz_alter_endframe_options_alter_quiz_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='icons',
            name='file',
            field=models.FileField(upload_to=Lending.models.random_icon_filename, verbose_name='Файл иконки'),
        ),
        migrations.AlterField(
            model_name='imageforexampleofwork',
            name='file',
            field=models.FileField(upload_to=Lending.models.random_example_filename, verbose_name='Файл примера работ'),
        ),
        migrations.AlterField(
            model_name='imagesquiz',
            name='file',
            field=models.FileField(upload_to=Lending.models.random_quiz_filename, verbose_name='Файл квиза'),
        ),
    ]
