# Generated by Django 5.1.4 on 2025-07-06 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0041_alter_icons_file_alter_imageforexampleofwork_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageforexampleofwork',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
        migrations.AddField(
            model_name='imagesquiz',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название файла'),
        ),
    ]
