# Generated by Django 5.1.4 on 2025-09-28 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Lending', '0041_utmexamplework_imageforexampleofwork_title_and_more'),
        ('Lending', '0042_imageforexampleofwork_title_imagesquiz_title'),
    ]

    operations = [
    ]
